/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/alextanhongpin/.choosenim/toolchains/nim-0.18.0/lib -o /Users/alextanhongpin/Documents/architecture/data-structures-and-algorithms/fibonacci/nim/tests/nimcache/fib_test1.o /Users/alextanhongpin/Documents/architecture/data-structures-and-algorithms/fibonacci/nim/tests/nimcache/fib_test1.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct tySequence_2gM6knqz8MaAY9c4MAR2ztg tySequence_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NU8 tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tySequence_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_5)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_GgW0QiD89cMFXShyPQ8t8qg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ)(NimStringDesc* currentSuiteName, NimStringDesc* testName);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_11)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(NI64, fibo_Mcf34EdyTl9chwdy9bexLQWw)(NI n);
N_LIB_PRIVATE N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_19)(void);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_23)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA)(Exception* e);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_24)(void);
static N_INLINE(void, popCurrentException)(void);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_27)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_29)(void);
N_LIB_PRIVATE N_NIMCALL(NU64, fib_dynamic_hiTH3e40sA9axVXN9czUSIew)(NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_35)(void);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_37)(void);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_38)(void);
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_41)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2)(void);
N_NIMCALL(void, chckNilDisp)(void* p);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_3pDl7sjdCupGLpWwbS2CHg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_fZDr7JVThcpXnuqtgFvwWQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, fib_fibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, fib_fibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, test1DatInit000)(void);
NimStringDesc* testSuiteName_EqjWuz5zs4aTTYfjOCLFdw;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA;
extern TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
extern tySequence_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
NIM_BOOL testSetupIMPLFlag_qNEanOqtjRdlOnDor9a52VA;
NIM_BOOL testTeardownIMPLFlag_mh2h9cYawEwpfCKVfyAPLrw;
extern tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_2;
NI64 colonc1__0k0ziSNLpKRxAvX5rLMpow;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_3;
extern NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
extern NI nim_program_result;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
NimStringDesc* stackTrace_04HVly4Qu9b9cnoRgpOZjzBA;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_4;
tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_6CUQXPXNkSKo0uVhqH2CvQ;
extern TNimType NTI_GEvSVSxdPWWgMGM48ywEYQ_;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_5;
NU64 colonc1__0k0ziSNLpKRxAvX5rLMpow_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_6;
NimStringDesc* stackTrace_04HVly4Qu9b9cnoRgpOZjzBA_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_Xtv7AUodw9bAKVqiPhMu2nA_7;
tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_6CUQXPXNkSKo0uVhqH2CvQ_2;
extern TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
static TNimType* Nim_OfCheck_CACHE45[2];
extern TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
static TNimType* Nim_OfCheck_CACHE46[2];
extern TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
static TNimType* Nim_OfCheck_CACHE47[2];
static TNimType* Nim_OfCheck_CACHE48[2];
static TNimType* Nim_OfCheck_CACHE49[2];
static TNimType* Nim_OfCheck_CACHE50[2];
static TNimType* Nim_OfCheck_CACHE51[2];
static TNimType* Nim_OfCheck_CACHE52[2];
static TNimType* Nim_OfCheck_CACHE53[2];
static TNimType* Nim_OfCheck_CACHE54[2];
static TNimType* Nim_OfCheck_CACHE55[2];
static TNimType* Nim_OfCheck_CACHE56[2];
static TNimType* Nim_OfCheck_CACHE57[2];
static TNimType* Nim_OfCheck_CACHE58[2];
static TNimType* Nim_OfCheck_CACHE59[2];
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_3, "testing fibonnaci", 17);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_7, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_9, "setting up fibonacci test", 25);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_e89aXorLyiDJyNvommr6mRQ_8 = {((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_9)}
;
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_10, "fib()", 5);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_15, "run before each test", 20);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_e89aXorLyiDJyNvommr6mRQ_14 = {((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_15)}
;
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_17, "test1.nim(13, 18): Check failed: fibo(5) == 5", 45);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_18, "fibo(5) was ", 12);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_21, "Unhandled exception: ", 21);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_22, "", 0);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_28, "fib_dynamic()", 13);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_33, "test1.nim(16, 25): Check failed: fib_dynamic(5) == 5", 52);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_34, "fib_dynamic(5) was ", 19);
STRING_LITERAL(TM_e89aXorLyiDJyNvommr6mRQ_43, "suite teardown: run once after the tests", 40);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_e89aXorLyiDJyNvommr6mRQ_42 = {((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_43)}
;
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_2)(void) {
	nimGCvisit((void*)testSuiteName_EqjWuz5zs4aTTYfjOCLFdw, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_5)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_11)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_2, 0);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_19)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_3, 0);
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void) {
	NimStringDesc* result;
	Exception* e;
	nimfr_("getCurrentExceptionMsg", "system.nim");
{	result = (NimStringDesc*)0;
	nimln_(3355, "system.nim");
	e = getCurrentException();
	nimln_(3356, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_22));
	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_23)(void) {
	nimGCvisit((void*)stackTrace_04HVly4Qu9b9cnoRgpOZjzBA, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_24)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_4, 0);
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_27)(void) {
	nimGCvisit((void*)testResult_6CUQXPXNkSKo0uVhqH2CvQ.suiteName, 0);
	nimGCvisit((void*)testResult_6CUQXPXNkSKo0uVhqH2CvQ.testName, 0);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_29)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_5, 0);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_35)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_6, 0);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_37)(void) {
	nimGCvisit((void*)stackTrace_04HVly4Qu9b9cnoRgpOZjzBA_2, 0);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_38)(void) {
	nimGCvisit((void*)formatter_Xtv7AUodw9bAKVqiPhMu2nA_7, 0);
}
static N_NIMCALL(void, TM_e89aXorLyiDJyNvommr6mRQ_41)(void) {
	nimGCvisit((void*)testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.suiteName, 0);
	nimGCvisit((void*)testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.testName, 0);
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_GgW0QiD89cMFXShyPQ8t8qg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim");
	nimln_(157, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE45)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), suiteName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE46)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteStarted_3pDl7sjdCupGLpWwbS2CHg(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), suiteName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE47)))) goto LA9_;
		suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA(formatter, suiteName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim");
	nimln_(159, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE48)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testStarted_EYS8dFM0pZmDNdV9c1cyo4Q(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE49)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testStarted_0WlfvTsMUPRHUfLeuXrGAg(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE50)))) goto LA9_;
		testStarted_YRuPwQXlDxZko9bSMypk3hA(formatter, testName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim");
	nimln_(161, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE51)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		failureOccurred_NAlHeCfOfz1bBvtw2rCPGw(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE52)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		failureOccurred_HopmjhtOQil8N9axQ5kNI3w(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE53)))) goto LA9_;
		failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw(formatter, checkpoints, stackTrace);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "unittest.nim");
	nimln_(165, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE54)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testEnded_E5f9a05hVCAPvYslPV2f4TQ(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testResult);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE55)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testEnded_fZDr7JVThcpXnuqtgFvwWQ(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testResult);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE56)))) goto LA9_;
		testEnded_hPRwDS9aOIRJ5MB9buAX30Wg(formatter, testResult);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim");
	nimln_(167, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE57)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteEnded_EF53BADEiH9a6amiy7eitMg_2(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)));
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE58)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)));
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE59)))) goto LA9_;
		suiteEnded_RS3dEHKAbuhOugXu1dXVHg(formatter);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_hashesDatInit000();
	stdlib_setsDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strformatDatInit000();
	stdlib_colorsDatInit000();
	stdlib_tablesDatInit000();
	stdlib_termiosDatInit000();
	stdlib_terminalDatInit000();
	stdlib_unittestDatInit000();
	fib_fibDatInit000();
	test1DatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_streamsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_hashesInit000();
	stdlib_setsInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_unicodeInit000();
	stdlib_strformatInit000();
	stdlib_colorsInit000();
	stdlib_tablesInit000();
	stdlib_termiosInit000();
	stdlib_terminalInit000();
	stdlib_unittestInit000();
	fib_fibInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("test1", "test1.nim");
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_2);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_5);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_11);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_19);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_23);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_24);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_27);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_29);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_35);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_37);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_38);
nimRegisterGlobalMarker(TM_e89aXorLyiDJyNvommr6mRQ_41);
	{
		NimStringDesc* T2_;
		TSafePoint TM_e89aXorLyiDJyNvommr6mRQ_4;
		nimln_(439, "unittest.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = testSuiteName_EqjWuz5zs4aTTYfjOCLFdw; testSuiteName_EqjWuz5zs4aTTYfjOCLFdw = copyStringRC1(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_3));
		if (T2_) nimGCunrefNoCycle(T2_);
		nimln_(441, "unittest.nim");
		ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
		nimln_(442, "unittest.nim");
		pushSafePoint(&TM_e89aXorLyiDJyNvommr6mRQ_4);
		TM_e89aXorLyiDJyNvommr6mRQ_4.status = _setjmp(TM_e89aXorLyiDJyNvommr6mRQ_4.context);
		if (TM_e89aXorLyiDJyNvommr6mRQ_4.status == 0) {
			{
				NI volatile i;
				NI L;
				NI T5_;
				nimln_(3805, "system.nim");
				i = ((NI) 0);
				nimln_(3806, "system.nim");
				T5_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
				L = T5_;
				{
					nimln_(3807, "system.nim");
					while (1) {
						NI TM_e89aXorLyiDJyNvommr6mRQ_6;
						if (!(i < L)) goto LA7;
						nimln_(3808, "system.nim");
						if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
						asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i]);
						nimln_(444, "unittest.nim");
						suiteStarted_GgW0QiD89cMFXShyPQ8t8qg(formatter_Xtv7AUodw9bAKVqiPhMu2nA, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_3));
						nimln_(3809, "system.nim");
						TM_e89aXorLyiDJyNvommr6mRQ_6 = addInt(i, ((NI) 1));
						i = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_6);
						nimln_(3810, "system.nim");
						{
							NI T10_;
							T10_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
							if (!!((T10_ == L))) goto LA11_;
							failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
						}
						LA11_: ;
					} LA7: ;
				}
			}
			nimln_(5, "test1.nim");
			echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_8, 1);
			nimln_(432, "unittest.nim");
			testSetupIMPLFlag_qNEanOqtjRdlOnDor9a52VA = NIM_TRUE;
			nimln_(436, "unittest.nim");
			testTeardownIMPLFlag_mh2h9cYawEwpfCKVfyAPLrw = NIM_TRUE;
			nimln_(465, "unittest.nim");
			ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
			nimln_(12, "test1.nim");
			{
				NIM_BOOL T15_;
				TSafePoint TM_e89aXorLyiDJyNvommr6mRQ_13;
				nimln_(467, "unittest.nim");
				T15_ = (NIM_BOOL)0;
				T15_ = shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ(testSuiteName_EqjWuz5zs4aTTYfjOCLFdw, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_10));
				if (!T15_) goto LA16_;
				nimln_(468, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				nimln_(469, "unittest.nim");
				testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
				{
					NI volatile i_2;
					NI L_2;
					NI T19_;
					nimln_(3805, "system.nim");
					i_2 = ((NI) 0);
					nimln_(3806, "system.nim");
					T19_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					L_2 = T19_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI TM_e89aXorLyiDJyNvommr6mRQ_12;
							if (!(i_2 < L_2)) goto LA21;
							nimln_(3808, "system.nim");
							if ((NU)(i_2) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_2), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_2]);
							nimln_(472, "unittest.nim");
							testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_Xtv7AUodw9bAKVqiPhMu2nA_2, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_10));
							nimln_(3809, "system.nim");
							TM_e89aXorLyiDJyNvommr6mRQ_12 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_12);
							nimln_(3810, "system.nim");
							{
								NI T24_;
								T24_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
								if (!!((T24_ == L_2))) goto LA25_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
							}
							LA25_: ;
						} LA21: ;
					}
				}
				nimln_(474, "unittest.nim");
				pushSafePoint(&TM_e89aXorLyiDJyNvommr6mRQ_13);
				TM_e89aXorLyiDJyNvommr6mRQ_13.status = _setjmp(TM_e89aXorLyiDJyNvommr6mRQ_13.context);
				if (TM_e89aXorLyiDJyNvommr6mRQ_13.status == 0) {
					TSafePoint TM_e89aXorLyiDJyNvommr6mRQ_16;
					nimln_(7, "test1.nim");
					echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_14, 1);
					nimln_(477, "unittest.nim");
					pushSafePoint(&TM_e89aXorLyiDJyNvommr6mRQ_16);
					TM_e89aXorLyiDJyNvommr6mRQ_16.status = _setjmp(TM_e89aXorLyiDJyNvommr6mRQ_16.context);
					if (TM_e89aXorLyiDJyNvommr6mRQ_16.status == 0) {
						{
							nimln_(583, "unittest.nim");
							colonc1__0k0ziSNLpKRxAvX5rLMpow = fibo_Mcf34EdyTl9chwdy9bexLQWw(((NI) 5));
							nimln_(636, "unittest.nim");
							{
								NimStringDesc* T34_;
								NimStringDesc* T35_;
								nimln_(633, "unittest.nim");
								nimln_(612, "unittest.nim");
								if (!!((colonc1__0k0ziSNLpKRxAvX5rLMpow == IL64(5)))) goto LA32_;
								nimln_(637, "unittest.nim");
								checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_17));
								nimln_(588, "unittest.nim");
								T34_ = (NimStringDesc*)0;
								nimln_(612, "unittest.nim");
								T35_ = (NimStringDesc*)0;
								T35_ = nimInt64ToStr(colonc1__0k0ziSNLpKRxAvX5rLMpow);
								T34_ = rawNewString(T35_->Sup.len + 12);
appendString(T34_, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_18));
appendString(T34_, T35_);
								checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T34_);
								nimln_(529, "unittest.nim");
								testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
								nimln_(533, "unittest.nim");
								ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
								{
									NI volatile i_3;
									NI L_3;
									NI T37_;
									nimln_(3805, "system.nim");
									i_3 = ((NI) 0);
									nimln_(3806, "system.nim");
									T37_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
									L_3 = T37_;
									{
										nimln_(3807, "system.nim");
										while (1) {
											NI TM_e89aXorLyiDJyNvommr6mRQ_20;
											if (!(i_3 < L_3)) goto LA39;
											nimln_(3808, "system.nim");
											if ((NU)(i_3) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
											asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_3), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_3]);
											nimln_(540, "unittest.nim");
											failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_Xtv7AUodw9bAKVqiPhMu2nA_3, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
											nimln_(3809, "system.nim");
											TM_e89aXorLyiDJyNvommr6mRQ_20 = addInt(i_3, ((NI) 1));
											i_3 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_20);
											nimln_(3810, "system.nim");
											{
												NI T42_;
												T42_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
												if (!!((T42_ == L_3))) goto LA43_;
												failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
											}
											LA43_: ;
										} LA39: ;
									}
								}
								nimln_(543, "unittest.nim");
								{
									if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA47_;
									exit(nim_program_result);
								}
								LA47_: ;
								nimln_(545, "unittest.nim");
								if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
								checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
							}
							LA32_: ;
						}
						popSafePoint();
					}
					else {
						popSafePoint();
						setFrame((TFrame*)&FR_);
					}
					{
						nimln_(10, "test1.nim");
						echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_14, 1);
					}
					if (TM_e89aXorLyiDJyNvommr6mRQ_16.status != 0) reraiseException();
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR_);
					{
						NimStringDesc* T53_;
						NimStringDesc* T54_;
						Exception* T55_;
						TM_e89aXorLyiDJyNvommr6mRQ_13.status = 0;
						nimln_(482, "unittest.nim");
						T53_ = (NimStringDesc*)0;
						T54_ = (NimStringDesc*)0;
						T54_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
						T53_ = rawNewString(T54_->Sup.len + 21);
appendString(T53_, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_21));
appendString(T53_, T54_);
						checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T53_);
						nimln_(483, "unittest.nim");
						T55_ = (Exception*)0;
						T55_ = getCurrentException();
						asgnRefNoCycle((void**) (&stackTrace_04HVly4Qu9b9cnoRgpOZjzBA), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T55_));
						nimln_(529, "unittest.nim");
						testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
						nimln_(533, "unittest.nim");
						ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
						{
							NI volatile i_4;
							NI L_4;
							NI T57_;
							nimln_(3805, "system.nim");
							i_4 = ((NI) 0);
							nimln_(3806, "system.nim");
							T57_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
							L_4 = T57_;
							{
								nimln_(3807, "system.nim");
								while (1) {
									NI TM_e89aXorLyiDJyNvommr6mRQ_25;
									if (!(i_4 < L_4)) goto LA59;
									nimln_(3808, "system.nim");
									if ((NU)(i_4) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
									asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_4), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_4]);
									nimln_(538, "unittest.nim");
									failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_Xtv7AUodw9bAKVqiPhMu2nA_4, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_04HVly4Qu9b9cnoRgpOZjzBA);
									nimln_(3809, "system.nim");
									TM_e89aXorLyiDJyNvommr6mRQ_25 = addInt(i_4, ((NI) 1));
									i_4 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_25);
									nimln_(3810, "system.nim");
									{
										NI T62_;
										T62_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
										if (!!((T62_ == L_4))) goto LA63_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
									}
									LA63_: ;
								} LA59: ;
							}
						}
						nimln_(543, "unittest.nim");
						{
							if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA67_;
							exit(nim_program_result);
						}
						LA67_: ;
						nimln_(545, "unittest.nim");
						if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
						checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
						popCurrentException();
					}
				}
				{
					NimStringDesc* T74_;
					NimStringDesc* T75_;
					nimln_(487, "unittest.nim");
					{
						NI TM_e89aXorLyiDJyNvommr6mRQ_26;
						if (!(testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA72_;
						nimln_(488, "unittest.nim");
						TM_e89aXorLyiDJyNvommr6mRQ_26 = addInt(nim_program_result, ((NI) 1));
						nim_program_result = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_26);
					}
					LA72_: ;
					nimln_(489, "unittest.nim");
					chckNil((void*)(&testResult_6CUQXPXNkSKo0uVhqH2CvQ));
					genericReset((void*)(&testResult_6CUQXPXNkSKo0uVhqH2CvQ), (&NTI_GEvSVSxdPWWgMGM48ywEYQ_));
					T74_ = (NimStringDesc*)0;
					T74_ = testResult_6CUQXPXNkSKo0uVhqH2CvQ.suiteName; testResult_6CUQXPXNkSKo0uVhqH2CvQ.suiteName = copyStringRC1(testSuiteName_EqjWuz5zs4aTTYfjOCLFdw);
					if (T74_) nimGCunrefNoCycle(T74_);
					T75_ = (NimStringDesc*)0;
					T75_ = testResult_6CUQXPXNkSKo0uVhqH2CvQ.testName; testResult_6CUQXPXNkSKo0uVhqH2CvQ.testName = copyStringRC1(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_10));
					if (T75_) nimGCunrefNoCycle(T75_);
					testResult_6CUQXPXNkSKo0uVhqH2CvQ.status = testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg;
					nimln_(494, "unittest.nim");
					testEnded_xoIS1BdhYWQ6hhMP22XXiw(testResult_6CUQXPXNkSKo0uVhqH2CvQ);
					nimln_(495, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				if (TM_e89aXorLyiDJyNvommr6mRQ_13.status != 0) reraiseException();
			}
			LA16_: ;
			nimln_(465, "unittest.nim");
			ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
			nimln_(15, "test1.nim");
			{
				NIM_BOOL T78_;
				TSafePoint TM_e89aXorLyiDJyNvommr6mRQ_31;
				nimln_(467, "unittest.nim");
				T78_ = (NIM_BOOL)0;
				T78_ = shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ(testSuiteName_EqjWuz5zs4aTTYfjOCLFdw, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_28));
				if (!T78_) goto LA79_;
				nimln_(468, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				nimln_(469, "unittest.nim");
				testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
				{
					NI volatile i_5;
					NI L_5;
					NI T82_;
					nimln_(3805, "system.nim");
					i_5 = ((NI) 0);
					nimln_(3806, "system.nim");
					T82_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					L_5 = T82_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI TM_e89aXorLyiDJyNvommr6mRQ_30;
							if (!(i_5 < L_5)) goto LA84;
							nimln_(3808, "system.nim");
							if ((NU)(i_5) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_5), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_5]);
							nimln_(472, "unittest.nim");
							testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_Xtv7AUodw9bAKVqiPhMu2nA_5, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_28));
							nimln_(3809, "system.nim");
							TM_e89aXorLyiDJyNvommr6mRQ_30 = addInt(i_5, ((NI) 1));
							i_5 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_30);
							nimln_(3810, "system.nim");
							{
								NI T87_;
								T87_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
								if (!!((T87_ == L_5))) goto LA88_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
							}
							LA88_: ;
						} LA84: ;
					}
				}
				nimln_(474, "unittest.nim");
				pushSafePoint(&TM_e89aXorLyiDJyNvommr6mRQ_31);
				TM_e89aXorLyiDJyNvommr6mRQ_31.status = _setjmp(TM_e89aXorLyiDJyNvommr6mRQ_31.context);
				if (TM_e89aXorLyiDJyNvommr6mRQ_31.status == 0) {
					TSafePoint TM_e89aXorLyiDJyNvommr6mRQ_32;
					nimln_(7, "test1.nim");
					echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_14, 1);
					nimln_(477, "unittest.nim");
					pushSafePoint(&TM_e89aXorLyiDJyNvommr6mRQ_32);
					TM_e89aXorLyiDJyNvommr6mRQ_32.status = _setjmp(TM_e89aXorLyiDJyNvommr6mRQ_32.context);
					if (TM_e89aXorLyiDJyNvommr6mRQ_32.status == 0) {
						{
							nimln_(583, "unittest.nim");
							colonc1__0k0ziSNLpKRxAvX5rLMpow_2 = fib_dynamic_hiTH3e40sA9axVXN9czUSIew(((NI) 5));
							nimln_(636, "unittest.nim");
							{
								NimStringDesc* T97_;
								NimStringDesc* T98_;
								nimln_(633, "unittest.nim");
								nimln_(612, "unittest.nim");
								if (!!((colonc1__0k0ziSNLpKRxAvX5rLMpow_2 == ((NI) 5)))) goto LA95_;
								nimln_(637, "unittest.nim");
								checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_33));
								nimln_(588, "unittest.nim");
								T97_ = (NimStringDesc*)0;
								nimln_(612, "unittest.nim");
								T98_ = (NimStringDesc*)0;
								T98_ = dollar__rzAI8EMyNBAQwGODeohhAA(colonc1__0k0ziSNLpKRxAvX5rLMpow_2);
								T97_ = rawNewString(T98_->Sup.len + 19);
appendString(T97_, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_34));
appendString(T97_, T98_);
								checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T97_);
								nimln_(529, "unittest.nim");
								testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
								nimln_(533, "unittest.nim");
								ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
								{
									NI volatile i_6;
									NI L_6;
									NI T100_;
									nimln_(3805, "system.nim");
									i_6 = ((NI) 0);
									nimln_(3806, "system.nim");
									T100_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
									L_6 = T100_;
									{
										nimln_(3807, "system.nim");
										while (1) {
											NI TM_e89aXorLyiDJyNvommr6mRQ_36;
											if (!(i_6 < L_6)) goto LA102;
											nimln_(3808, "system.nim");
											if ((NU)(i_6) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
											asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_6), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_6]);
											nimln_(540, "unittest.nim");
											failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_Xtv7AUodw9bAKVqiPhMu2nA_6, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
											nimln_(3809, "system.nim");
											TM_e89aXorLyiDJyNvommr6mRQ_36 = addInt(i_6, ((NI) 1));
											i_6 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_36);
											nimln_(3810, "system.nim");
											{
												NI T105_;
												T105_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
												if (!!((T105_ == L_6))) goto LA106_;
												failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
											}
											LA106_: ;
										} LA102: ;
									}
								}
								nimln_(543, "unittest.nim");
								{
									if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA110_;
									exit(nim_program_result);
								}
								LA110_: ;
								nimln_(545, "unittest.nim");
								if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
								checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
							}
							LA95_: ;
						}
						popSafePoint();
					}
					else {
						popSafePoint();
						setFrame((TFrame*)&FR_);
					}
					{
						nimln_(10, "test1.nim");
						echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_14, 1);
					}
					if (TM_e89aXorLyiDJyNvommr6mRQ_32.status != 0) reraiseException();
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR_);
					{
						NimStringDesc* T116_;
						NimStringDesc* T117_;
						Exception* T118_;
						TM_e89aXorLyiDJyNvommr6mRQ_31.status = 0;
						nimln_(482, "unittest.nim");
						T116_ = (NimStringDesc*)0;
						T117_ = (NimStringDesc*)0;
						T117_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
						T116_ = rawNewString(T117_->Sup.len + 21);
appendString(T116_, ((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_21));
appendString(T116_, T117_);
						checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T116_);
						nimln_(483, "unittest.nim");
						T118_ = (Exception*)0;
						T118_ = getCurrentException();
						asgnRefNoCycle((void**) (&stackTrace_04HVly4Qu9b9cnoRgpOZjzBA_2), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T118_));
						nimln_(529, "unittest.nim");
						testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
						nimln_(533, "unittest.nim");
						ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
						{
							NI volatile i_7;
							NI L_7;
							NI T120_;
							nimln_(3805, "system.nim");
							i_7 = ((NI) 0);
							nimln_(3806, "system.nim");
							T120_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
							L_7 = T120_;
							{
								nimln_(3807, "system.nim");
								while (1) {
									NI TM_e89aXorLyiDJyNvommr6mRQ_39;
									if (!(i_7 < L_7)) goto LA122;
									nimln_(3808, "system.nim");
									if ((NU)(i_7) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
									asgnRef((void**) (&formatter_Xtv7AUodw9bAKVqiPhMu2nA_7), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_7]);
									nimln_(538, "unittest.nim");
									failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_Xtv7AUodw9bAKVqiPhMu2nA_7, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_04HVly4Qu9b9cnoRgpOZjzBA_2);
									nimln_(3809, "system.nim");
									TM_e89aXorLyiDJyNvommr6mRQ_39 = addInt(i_7, ((NI) 1));
									i_7 = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_39);
									nimln_(3810, "system.nim");
									{
										NI T125_;
										T125_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
										if (!!((T125_ == L_7))) goto LA126_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_7));
									}
									LA126_: ;
								} LA122: ;
							}
						}
						nimln_(543, "unittest.nim");
						{
							if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA130_;
							exit(nim_program_result);
						}
						LA130_: ;
						nimln_(545, "unittest.nim");
						if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
						checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
						popCurrentException();
					}
				}
				{
					NimStringDesc* T137_;
					NimStringDesc* T138_;
					nimln_(487, "unittest.nim");
					{
						NI TM_e89aXorLyiDJyNvommr6mRQ_40;
						if (!(testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2 == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA135_;
						nimln_(488, "unittest.nim");
						TM_e89aXorLyiDJyNvommr6mRQ_40 = addInt(nim_program_result, ((NI) 1));
						nim_program_result = (NI)(TM_e89aXorLyiDJyNvommr6mRQ_40);
					}
					LA135_: ;
					nimln_(489, "unittest.nim");
					chckNil((void*)(&testResult_6CUQXPXNkSKo0uVhqH2CvQ_2));
					genericReset((void*)(&testResult_6CUQXPXNkSKo0uVhqH2CvQ_2), (&NTI_GEvSVSxdPWWgMGM48ywEYQ_));
					T137_ = (NimStringDesc*)0;
					T137_ = testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.suiteName; testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.suiteName = copyStringRC1(testSuiteName_EqjWuz5zs4aTTYfjOCLFdw);
					if (T137_) nimGCunrefNoCycle(T137_);
					T138_ = (NimStringDesc*)0;
					T138_ = testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.testName; testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.testName = copyStringRC1(((NimStringDesc*) &TM_e89aXorLyiDJyNvommr6mRQ_28));
					if (T138_) nimGCunrefNoCycle(T138_);
					testResult_6CUQXPXNkSKo0uVhqH2CvQ_2.status = testStatusIMPL_b9aWgJ9cY2VZgxsrswE6ZFLg_2;
					nimln_(494, "unittest.nim");
					testEnded_xoIS1BdhYWQ6hhMP22XXiw(testResult_6CUQXPXNkSKo0uVhqH2CvQ_2);
					nimln_(495, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				if (TM_e89aXorLyiDJyNvommr6mRQ_31.status != 0) reraiseException();
			}
			LA79_: ;
			nimln_(18, "test1.nim");
			echoBinSafe(TM_e89aXorLyiDJyNvommr6mRQ_42, 1);
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			nimln_(447, "unittest.nim");
			suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2();
		}
		if (TM_e89aXorLyiDJyNvommr6mRQ_4.status != 0) reraiseException();
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, test1DatInit000)(void) {
}

