/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/alextanhongpin/.choosenim/toolchains/nim-0.18.0/lib -o /Users/alextanhongpin/Documents/architecture/data-structures-and-algorithms/fibonacci/nim/tests/nimcache/stdlib_unittest.o /Users/alextanhongpin/Documents/architecture/data-structures-and-algorithms/fibonacci/nim/tests/nimcache/stdlib_unittest.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_2gM6knqz8MaAY9c4MAR2ztg tySequence_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct RootObj RootObj;
typedef struct tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg;
typedef struct tySequence_4eRCaZmrYLLw2k30GPTiMw tySequence_4eRCaZmrYLLw2k30GPTiMw;
typedef struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw tyTuple_QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg {
tySequence_4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
typedef NU8 tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
typedef NU8 tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringDesc* tyArray_haiLFy0nBviVTKFGuwztzQ[5];
struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
typedef NU8 tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ;
struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
struct tySequence_4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple_QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tyRef_po6hYFavJCZm28qf1dR3mw)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_4)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv_vAQ9aK36dVeMFf61ovfHwJw)(NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_LIB_PRIVATE N_NIMCALL(void, addOutputFormatter_4nkd7g9ax9bLTtQYMNO9cp0Ag)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__z9cxc4k8iqgnw41zdA8grdw)(tySequence_2gM6knqz8MaAY9c4MAR2ztg* x, tySequence_2gM6knqz8MaAY9c4MAR2ztg* y);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw)(tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput);
static N_NIMCALL(void, Marker_tyRef_ExFEz8ninaqkX3e4eolu7g)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_3pDl7sjdCupGLpWwbS2CHg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, setStyle_QybHW7qWiqgJClj5g4HJsQ)(FILE* f, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_pQ6uHp6t9ccVTSBEnIyzxsA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_fZDr7JVThcpXnuqtgFvwWQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*, newJUnitOutputFormatter_PqqpGJPZVHC1k3JX9cfStQQ)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream);
static N_NIMCALL(void, Marker_tyRef_OU9b9b9b3svfAf0YBTEFQsJag)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, writeLine_G1TKFmud9akiH9bzSHWMshag_2)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, close_EF53BADEiH9a6amiy7eitMg)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_LIB_PRIVATE N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NF, ntepochTime)(void);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, add_sp11IzYl5roq19bn4qRQmqA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** x, NimStringDesc** y, NI yLen_0);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ format, NI precision, NIM_CHAR decimalSep);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
static N_INLINE(NimStringDesc**, X5BX5D__xFULIkGrri8iJzi40N9ahqwunittest)(NimStringDesc** s, NI sLen_0, NI i);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob_C0DsE6YhGRKuvHmSh8PDlg)(NimStringDesc* matcher, NimStringDesc* filter);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter_pLZsRuqSngMO8AW9bwoOkuA)(NimStringDesc* suiteName, NimStringDesc* testName, NimStringDesc* filter);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ)(NimStringDesc* currentSuiteName, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(NI, len_0AUATxCKyjOFDOv0xWITWA)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid_6eOTx6voj6zxXrOLagnuRg)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s);
static N_INLINE(NIM_BOOL, isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void);
N_LIB_PRIVATE N_NIMCALL(void, init_dG7qwLANa3DTWvQLq7ZA7g)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg* s, NI initialSize);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_LIB_PRIVATE N_NIMCALL(void, incl_I6VFHFuzEfqdUNaUfyr6kA)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg* s, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__SRlIwYUUH1G46Yee9aMIFAQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* y);
static N_INLINE(NI, rawGet_SaVNwZAzzx9cfbfqIaCbK7Qsets)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NI, nextTry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h, NI maxHash);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_AdJq4wBW1P1lPO9b8ZHnO2g)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg* s);
static N_INLINE(NI, rawGetKnownHC_CuJUY9aKh8Ku1t1T7BDJRuQsets)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_NHve4XdmAn7u81IC9bnRBng)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg* s, tySequence_4eRCaZmrYLLw2k30GPTiMw** data, NimStringDesc* key, NI hc, NI h);
NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
tySequence_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
TNimType NTI_2gM6knqz8MaAY9c4MAR2ztg_;
tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg testsFilters_Xhcy9bMKRibp73mpqIGgoPA;
extern TNimType NTI_pOhUohTPuRItuGmDY0Ddzg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_7UfTrIPsm9cGDPwH9bpwJDww_;
TNimType NTI_ExFEz8ninaqkX3e4eolu7g_;
TNimType NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_;
TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
extern TNimType NTI_r3Wc5tOoxP8rz1DvGVTUvw_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_OU9b9b9b3svfAf0YBTEFQsJag_;
TNimType NTI_GEvSVSxdPWWgMGM48ywEYQ_;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_5, "NIMTEST_ABORT_ON_ERROR", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_10, "NIMTEST_OUTPUT_LVL", 18);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_11, "", 0);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_12, "NIMTEST_NO_COLOR", 16);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_14, "\012[Suite] ", 9);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_15, "\012", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_16, "    ", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_18, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_19, "  ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_20, "[", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_24, "] ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_25, "&lt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_26, "&gt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_27, "&amp;", 5);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_28, "&quot;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_29, "&apos;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_30, "&#", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_32, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_35, "<\?xml version=\"1.0\" encoding=\"UTF-8\"\?>", 38);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_34 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_35)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_37, "<testsuites>", 12);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_36 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_37)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_39, "</testsuites>", 13);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_38 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_39)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_40, "\011<testsuite name=\"$1\">", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_41, "\011\011<testcase name=\"$#\" time=\"$#\">", 32);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_43, "<skipped />", 11);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_42 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_43)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_45, "The test failed without outputting an error", 43);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_49, "\011\011\011<error message=\"$#\">$#</error>", 33);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_50, "\011\011\011<system-err>$#</system-err>", 30);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_51, "\011\011\011<failure message=\"$#\">$#</failure>", 37);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_53, "\011\011</testcase>", 13);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_52 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_53)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_55, "\011</testsuite>", 13);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_54 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_55)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_57, "::", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_58, "isValid(s) The set needs to be initialized.", 43);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void) {
	nimGCvisit((void*)checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, 0);
}
static N_NIMCALL(void, Marker_tyRef_po6hYFavJCZm28qf1dR3mw)(void* p, NI op) {
	tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* a;
	a = (tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)p;
}
static N_NIMCALL(void, Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op) {
	tySequence_2gM6knqz8MaAY9c4MAR2ztg* a;
	NI T1_;
	a = (tySequence_2gM6knqz8MaAY9c4MAR2ztg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void) {
	nimGCvisit((void*)formatters_55U7g4zhjHV9bCI6emTgDiA, 0);
}
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_4)(void) {
	nimGCvisit((void*)testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "unittest.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim");
	popFrame();
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addOutputFormatter_4nkd7g9ax9bLTtQYMNO9cp0Ag)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("addOutputFormatter", "unittest.nim");
	nimln_(171, "unittest.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__z9cxc4k8iqgnw41zdA8grdw(formatters_55U7g4zhjHV9bCI6emTgDiA, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(172, "unittest.nim");
		if (formatters_55U7g4zhjHV9bCI6emTgDiA) { nimGCunrefRC1(formatters_55U7g4zhjHV9bCI6emTgDiA); formatters_55U7g4zhjHV9bCI6emTgDiA = NIM_NIL; }
		formatters_55U7g4zhjHV9bCI6emTgDiA = (tySequence_2gM6knqz8MaAY9c4MAR2ztg*) newSeqRC1((&NTI_2gM6knqz8MaAY9c4MAR2ztg_), 1);
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[0]), formatter);
	}
	goto LA1_;
	LA4_: ;
	{
		NI T7_;
		nimln_(174, "unittest.nim");
		formatters_55U7g4zhjHV9bCI6emTgDiA = (tySequence_2gM6knqz8MaAY9c4MAR2ztg*) incrSeqV2(&(formatters_55U7g4zhjHV9bCI6emTgDiA)->Sup, sizeof(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*));
		T7_ = formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len++;
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[T7_]), formatter);
	}
	LA1_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_ExFEz8ninaqkX3e4eolu7g)(void* p, NI op) {
	tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* a;
	a = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw)(tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput) {
	tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* result;
	tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* T1_;
	nimfr_("newConsoleOutputFormatter", "unittest.nim");
	result = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	nimln_(178, "unittest.nim");
	T1_ = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	T1_ = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) newObj((&NTI_ExFEz8ninaqkX3e4eolu7g_), sizeof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw));
	(*T1_).Sup.Sup.m_type = (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_);
	(*T1_).outputLevel = outputLevel;
	(*T1_).colorOutput = colorOutput;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg)(void) {
	tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* result;
	NimStringDesc* envOutLvl;
	NIM_BOOL colorOutput;
	NIM_BOOL T1_;
	tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
	nimfr_("defaultConsoleFormatter", "unittest.nim");
	result = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	nimln_(187, "unittest.nim");
	envOutLvl = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_10), ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
	nimln_(188, "unittest.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = existsEnv_vAQ9aK36dVeMFf61ovfHwJw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_12));
	colorOutput = !(T1_);
	nimln_(189, "unittest.nim");
	outputLevel = ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0);
	nimln_(190, "unittest.nim");
	{
		if (!(((NI) 0) < (envOutLvl ? envOutLvl->Sup.len : 0))) goto LA4_;
		{
			tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww opt;
			NI res;
			opt = (tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww)0;
			nimln_(2032, "system.nim");
			res = ((NI) 0);
			{
				nimln_(2033, "system.nim");
				while (1) {
					NI TM_Um3CQPZ9bILAIolZOsxNIaw_13;
					if (!(res <= ((NI) 2))) goto LA8;
					nimln_(2034, "system.nim");
					opt = ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww)chckRange(res, ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0), ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 2)));
					nimln_(192, "unittest.nim");
					{
						if (!eqStrings(reprEnum((NI)opt, (&NTI_7UfTrIPsm9cGDPwH9bpwJDww_)), envOutLvl)) goto LA11_;
						nimln_(193, "unittest.nim");
						outputLevel = opt;
						nimln_(194, "unittest.nim");
						goto LA6;
					}
					LA11_: ;
					nimln_(2035, "system.nim");
					TM_Um3CQPZ9bILAIolZOsxNIaw_13 = addInt(res, ((NI) 1));
					res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_13);
				} LA8: ;
			}
		} LA6: ;
	}
	LA4_: ;
	nimln_(195, "unittest.nim");
	result = newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw(outputLevel, colorOutput);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_3pDl7sjdCupGLpWwbS2CHg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim");
	nimln_(202, "unittest.nim");
	{
		if (!(*formatter).colorOutput) goto LA3_;
		nimln_(713, "terminal.nim");
		setStyle_QybHW7qWiqgJClj5g4HJsQ(stdout, 1);
		setForegroundColor_pQ6uHp6t9ccVTSBEnIyzxsA(stdout, ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 34), NIM_FALSE);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_14));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, suiteName);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	}
	goto LA1_;
	LA3_: ;
	{
		tyArray_Re75IspeoxXy2oCZHwcRrA T6_;
		nimln_(200, "unittest.nim");
		memset((void*)T6_, 0, sizeof(T6_));
		T6_[0] = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_14));
		T6_[1] = copyString(suiteName);
		echoBinSafe(T6_, 2);
	}
	LA1_: ;
	nimln_(206, "unittest.nim");
	(*formatter).isInSuite = NIM_TRUE;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim");
	nimln_(209, "unittest.nim");
	(*formatter).isInTest = NIM_TRUE;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	NimStringDesc* prefix;
	nimfr_("failureOccurred", "unittest.nim");
	nimln_(212, "unittest.nim");
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
		nimln_(398, "system.nim");
		nimln_(212, "unittest.nim");
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		nimln_(213, "unittest.nim");
		memset((void*)T5_, 0, sizeof(T5_));
		T5_[0] = copyString(stackTrace);
		echoBinSafe(T5_, 1);
	}
	LA3_: ;
	nimln_(214, "unittest.nim");
	{
		if (!(*formatter).isInSuite) goto LA8_;
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_16));
	}
	goto LA6_;
	LA8_: ;
	{
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
	}
	LA6_: ;
	{
		NimStringDesc* msg;
		NI i;
		NI L;
		NI T12_;
		msg = (NimStringDesc*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T12_ = (checkpoints ? checkpoints->Sup.len : 0);
		L = T12_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				tyArray_Re75IspeoxXy2oCZHwcRrA T15_;
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_17;
				if (!(i < L)) goto LA14;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(checkpoints->Sup.len)) raiseIndexError();
				msg = checkpoints->data[i];
				nimln_(216, "unittest.nim");
				memset((void*)T15_, 0, sizeof(T15_));
				T15_[0] = copyString(prefix);
				T15_[1] = copyString(msg);
				echoBinSafe(T15_, 2);
				nimln_(3809, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_17 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_17);
				nimln_(3810, "system.nim");
				{
					NI T18_;
					T18_ = (checkpoints ? checkpoints->Sup.len : 0);
					if (!!((T18_ == L))) goto LA19_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_18));
				}
				LA19_: ;
			} LA14: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_fZDr7JVThcpXnuqtgFvwWQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "unittest.nim");
	nimln_(219, "unittest.nim");
	(*formatter).isInTest = NIM_FALSE;
	nimln_(221, "unittest.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T5_;
		NimStringDesc* prefix;
		T3_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(221, "unittest.nim");
		T3_ = !(((*formatter).outputLevel == ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 2)));
		if (!(T3_)) goto LA4_;
		nimln_(222, "unittest.nim");
		T5_ = (NIM_BOOL)0;
		T5_ = ((*formatter).outputLevel == ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0));
		if (T5_) goto LA6_;
		T5_ = (testResult.status == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1));
		LA6_: ;
		T3_ = T5_;
		LA4_: ;
		if (!T3_) goto LA7_;
		nimln_(223, "unittest.nim");
		{
			nimln_(398, "system.nim");
			nimln_(223, "unittest.nim");
			if (!!((testResult.suiteName == NIM_NIL))) goto LA11_;
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_19));
		}
		goto LA9_;
		LA11_: ;
		{
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
		}
		LA9_: ;
		nimln_(226, "unittest.nim");
		{
			NIM_BOOL T16_;
			tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg color;
			T16_ = (NIM_BOOL)0;
			T16_ = (*formatter).colorOutput;
			if (!(T16_)) goto LA17_;
			T16_ = NIM_TRUE;
			LA17_: ;
			if (!T16_) goto LA18_;
			nimln_(227, "unittest.nim");
			switch (testResult.status) {
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 32);
			}
			break;
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 31);
			}
			break;
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 33);
			}
			break;
			default:
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 37);
			}
			break;
			}
			nimln_(713, "terminal.nim");
			setStyle_QybHW7qWiqgJClj5g4HJsQ(stdout, 1);
			setForegroundColor_pQ6uHp6t9ccVTSBEnIyzxsA(stdout, color, NIM_FALSE);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, prefix);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_20));
			nimln_(232, "unittest.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, reprEnum((NI)testResult.status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_)));
			nimln_(713, "terminal.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_24));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, testResult.testName);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
		}
		goto LA14_;
		LA18_: ;
		{
			tyArray_haiLFy0nBviVTKFGuwztzQ T25_;
			nimln_(224, "unittest.nim");
			memset((void*)T25_, 0, sizeof(T25_));
			T25_[0] = copyString(prefix);
			T25_[1] = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_20));
			T25_[2] = reprEnum((NI)testResult.status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_));
			T25_[3] = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_24));
			T25_[4] = copyString(testResult.testName);
			echoBinSafe(T25_, 5);
		}
		LA14_: ;
	}
	LA7_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter) {
	nimfr_("suiteEnded", "unittest.nim");
	nimln_(239, "unittest.nim");
	(*formatter).isInSuite = NIM_FALSE;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("xmlEscape", "unittest.nim");
	result = (NimStringDesc*)0;
	nimln_(242, "unittest.nim");
	result = rawNewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(3823, "system.nim");
		i = ((NI) 0);
		nimln_(3824, "system.nim");
		L = (s ? s->Sup.len : 0);
		{
			nimln_(3825, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_31;
				if (!(i < L)) goto LA3;
				nimln_(3826, "system.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				c = s->data[i];
				nimln_(244, "unittest.nim");
				switch (((NU8)(c))) {
				case 60:
				{
					nimln_(245, "unittest.nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_25));
				}
				break;
				case 62:
				{
					nimln_(246, "unittest.nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_26));
				}
				break;
				case 38:
				{
					nimln_(247, "unittest.nim");
					result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_27));
				}
				break;
				case 34:
				{
					nimln_(248, "unittest.nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_28));
				}
				break;
				case 39:
				{
					nimln_(249, "unittest.nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_29));
				}
				break;
				default:
				{
					nimln_(251, "unittest.nim");
					{
						NimStringDesc* T14_;
						NimStringDesc* T15_;
						if (!(((NU8)(c)) < ((NI) 32))) goto LA12_;
						nimln_(252, "unittest.nim");
						T14_ = (NimStringDesc*)0;
						T15_ = (NimStringDesc*)0;
						T15_ = nimIntToStr(((NU8)(c)));
						T14_ = rawNewString(T15_->Sup.len + 3);
appendString(T14_, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_30));
appendString(T14_, T15_);
appendChar(T14_, 59);
						result = resizeString(result, T14_->Sup.len + 0);
appendString(result, T14_);
					}
					goto LA10_;
					LA12_: ;
					{
						nimln_(254, "unittest.nim");
						result = addChar(result, c);
					}
					LA10_: ;
				}
				break;
				}
				nimln_(3827, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_31 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_31);
				nimln_(3828, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA19_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_32));
				}
				LA19_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_OU9b9b9b3svfAf0YBTEFQsJag)(void* p, NI op) {
	tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* a;
	a = (tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)p;
	nimGCvisit((void*)(*a).stream, op);
	nimGCvisit((void*)(*a).testErrors, op);
	nimGCvisit((void*)(*a).testStackTrace, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*, newJUnitOutputFormatter_PqqpGJPZVHC1k3JX9cfStQQ)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream) {
	tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* result;
	tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* T1_;
	NimStringDesc* T2_;
	nimfr_("newJUnitOutputFormatter", "unittest.nim");
	result = (tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)0;
	nimln_(262, "unittest.nim");
	T1_ = (tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)0;
	T1_ = (tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) newObj((&NTI_OU9b9b9b3svfAf0YBTEFQsJag_), sizeof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ));
	(*T1_).Sup.Sup.m_type = (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_);
	asgnRef((void**) (&(*T1_).stream), stream);
	if ((*T1_).testErrors) { nimGCunrefNoCycle((*T1_).testErrors); (*T1_).testErrors = NIM_NIL; }
	(*T1_).testErrors = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).testStackTrace; (*T1_).testStackTrace = copyStringRC1(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
	if (T2_) nimGCunrefNoCycle(T2_);
	(*T1_).testStartTime = 0.0;
	result = T1_;
	nimln_(268, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, TM_Um3CQPZ9bILAIolZOsxNIaw_34, 1);
	nimln_(269, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, TM_Um3CQPZ9bILAIolZOsxNIaw_36, 1);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_EF53BADEiH9a6amiy7eitMg)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter) {
	nimfr_("close", "unittest.nim");
	nimln_(273, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_38, 1);
	nimln_(274, "unittest.nim");
	close_4ed7IXme7lqtClFI7s2sTQ_2((*formatter).stream);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* T2_;
	nimfr_("suiteStarted", "unittest.nim");
	nimln_(277, "unittest.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NimStringDesc*)0;
	T2_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ(suiteName);
	T1_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_40), T2_);
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T1_, 1);
	popFrame();
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim");
	nimln_(280, "unittest.nim");
	(*formatter).testErrors = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*formatter).testErrors)->Sup, sizeof(NimStringDesc*), ((NI) 0));
	nimln_(281, "unittest.nim");
	(*formatter).testStackTrace = setLengthStr((*formatter).testStackTrace, ((NI) 0));
	nimln_(282, "unittest.nim");
	(*formatter).testStartTime = ntepochTime();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim");
	nimln_(287, "unittest.nim");
	add_sp11IzYl5roq19bn4qRQmqA((&(*formatter).testErrors), checkpoints->data, checkpoints->Sup.len);
	nimln_(288, "unittest.nim");
	{
		NimStringDesc* T5_;
		nimln_(398, "system.nim");
		nimln_(288, "unittest.nim");
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		nimln_(289, "unittest.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*formatter).testStackTrace; (*formatter).testStackTrace = copyStringRC1(stackTrace);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc**, X5BX5D__xFULIkGrri8iJzi40N9ahqwunittest)(NimStringDesc** s, NI sLen_0, NI i) {
	NimStringDesc** result;
	NI TM_Um3CQPZ9bILAIolZOsxNIaw_44;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc**)0;
	nimln_(3629, "system.nim");
	TM_Um3CQPZ9bILAIolZOsxNIaw_44 = subInt(sLen_0, i);
	if ((NU)((NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_44)) >= (NU)(sLen_0)) raiseIndexError();
	result = (&s[(NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_44)]);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	NF time_1;
	NF T1_;
	NimStringDesc* timeStr;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T3_;
	nimfr_("testEnded", "unittest.nim");
	nimln_(292, "unittest.nim");
	T1_ = (NF)0;
	T1_ = ntepochTime();
	time_1 = ((NF)(T1_) - (NF)((*formatter).testStartTime));
	nimln_(293, "unittest.nim");
	timeStr = nsuformatFloat(time_1, ((tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ) 1), ((NI) 8), 46);
	nimln_(294, "unittest.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ(testResult.testName);
	T3_[1] = copyString(timeStr);
	T2_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_41), T3_, 2);
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T2_, 1);
	nimln_(295, "unittest.nim");
	switch (testResult.status) {
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
	{
	}
	break;
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
	{
		nimln_(299, "unittest.nim");
		writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_42, 1);
	}
	break;
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
	{
		NimStringDesc* failureMsg;
		NimStringDesc* errs;
		nimln_(301, "unittest.nim");
		{
			NIM_BOOL T9_;
			NI T11_;
			NimStringDesc** T14_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0));
			if (!(T9_)) goto LA10_;
			nimln_(302, "unittest.nim");
			T11_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			T9_ = (((NI) 0) < T11_);
			LA10_: ;
			if (!T9_) goto LA12_;
			nimln_(303, "unittest.nim");
			T14_ = (NimStringDesc**)0;
			T14_ = X5BX5D__xFULIkGrri8iJzi40N9ahqwunittest((*formatter).testErrors->data, (*formatter).testErrors->Sup.len, ((NI) 1));
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*T14_));
		}
		goto LA7_;
		LA12_: ;
		{
			NI T16_;
			nimln_(304, "unittest.nim");
			T16_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 0) < T16_)) goto LA17_;
			nimln_(305, "unittest.nim");
			if ((NU)(((NI) 0)) >= (NU)((*formatter).testErrors->Sup.len)) raiseIndexError();
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[((NI) 0)]);
		}
		goto LA7_;
		LA17_: ;
		{
			failureMsg = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_45));
		}
		LA7_: ;
		nimln_(308, "unittest.nim");
		errs = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
		nimln_(309, "unittest.nim");
		{
			NI T22_;
			NI startIdx;
			NI endIdx;
			T22_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 1) < T22_)) goto LA23_;
			nimln_(310, "unittest.nim");
			{
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA27_;
				startIdx = ((NI) 0);
			}
			goto LA25_;
			LA27_: ;
			{
				startIdx = ((NI) 1);
			}
			LA25_: ;
			nimln_(311, "unittest.nim");
			{
				NI T34_;
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_46;
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA32_;
				T34_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				TM_Um3CQPZ9bILAIolZOsxNIaw_46 = subInt(T34_, ((NI) 2));
				endIdx = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_46);
			}
			goto LA30_;
			LA32_: ;
			{
				NI T36_;
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_47;
				nimln_(312, "unittest.nim");
				T36_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				TM_Um3CQPZ9bILAIolZOsxNIaw_47 = subInt(T36_, ((NI) 1));
				endIdx = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_47);
			}
			LA30_: ;
			{
				NI errIdx;
				NI res;
				errIdx = (NI)0;
				nimln_(2045, "system.nim");
				res = startIdx;
				{
					nimln_(2046, "system.nim");
					while (1) {
						NimStringDesc* T44_;
						NI TM_Um3CQPZ9bILAIolZOsxNIaw_48;
						if (!(res <= endIdx)) goto LA39;
						nimln_(2047, "system.nim");
						errIdx = res;
						nimln_(315, "unittest.nim");
						{
							if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA42_;
							nimln_(316, "unittest.nim");
							errs = resizeString(errs, 1);
appendString(errs, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
						}
						LA42_: ;
						nimln_(317, "unittest.nim");
						if ((NU)(errIdx) >= (NU)((*formatter).testErrors->Sup.len)) raiseIndexError();
						T44_ = (NimStringDesc*)0;
						T44_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[errIdx]);
						errs = resizeString(errs, T44_->Sup.len + 0);
appendString(errs, T44_);
						nimln_(2048, "system.nim");
						TM_Um3CQPZ9bILAIolZOsxNIaw_48 = addInt(res, ((NI) 1));
						res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_48);
					} LA39: ;
				}
			}
		}
		LA23_: ;
		nimln_(319, "unittest.nim");
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T49_;
			tyArray_Re75IspeoxXy2oCZHwcRrA T50_;
			if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA47_;
			nimln_(320, "unittest.nim");
			memset((void*)T49_, 0, sizeof(T49_));
			memset((void*)T50_, 0, sizeof(T50_));
			T50_[0] = copyString(failureMsg);
			T50_[1] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testStackTrace);
			T49_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_49), T50_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T49_, 1);
			nimln_(321, "unittest.nim");
			{
				tyArray_nHXaesL0DJZHyVS07ARPRA T55_;
				if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA53_;
				nimln_(322, "unittest.nim");
				memset((void*)T55_, 0, sizeof(T55_));
				T55_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_50), errs);
				writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T55_, 1);
			}
			LA53_: ;
		}
		goto LA45_;
		LA47_: ;
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T57_;
			tyArray_Re75IspeoxXy2oCZHwcRrA T58_;
			nimln_(324, "unittest.nim");
			memset((void*)T57_, 0, sizeof(T57_));
			memset((void*)T58_, 0, sizeof(T58_));
			T58_[0] = copyString(failureMsg);
			T58_[1] = copyString(errs);
			T57_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_51), T58_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T57_, 1);
		}
		LA45_: ;
	}
	break;
	}
	nimln_(326, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_52, 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter) {
	nimfr_("suiteEnded", "unittest.nim");
	nimln_(329, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_54, 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob_C0DsE6YhGRKuvHmSh8PDlg)(NimStringDesc* matcher, NimStringDesc* filter) {
	NIM_BOOL result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* beforeAndAfter;
	NIM_BOOL T19_;
	nimfr_("glob", "unittest.nim");
{	result = (NIM_BOOL)0;
	nimln_(333, "unittest.nim");
	{
		if (!((filter ? filter->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(334, "unittest.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(336, "unittest.nim");
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = contains_6e5MGL10HDAJ205lBYpWxw(filter, 42);
		if (!!(T7_)) goto LA8_;
		nimln_(337, "unittest.nim");
		result = eqStrings(matcher, filter);
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(339, "unittest.nim");
	beforeAndAfter = nsuSplitChar(filter, 42, ((NI) 1));
	nimln_(340, "unittest.nim");
	{
		NI T12_;
		T12_ = (beforeAndAfter ? beforeAndAfter->Sup.len : 0);
		if (!(T12_ == ((NI) 1))) goto LA13_;
		nimln_(342, "unittest.nim");
		if ((NU)(((NI) 0)) >= (NU)(beforeAndAfter->Sup.len)) raiseIndexError();
		result = nsuStartsWith(matcher, beforeAndAfter->data[((NI) 0)]);
		goto BeforeRet_;
	}
	LA13_: ;
	nimln_(344, "unittest.nim");
	{
		NI TM_Um3CQPZ9bILAIolZOsxNIaw_56;
		TM_Um3CQPZ9bILAIolZOsxNIaw_56 = subInt((filter ? filter->Sup.len : 0), ((NI) 1));
		if (!((matcher ? matcher->Sup.len : 0) < (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_56))) goto LA17_;
		nimln_(345, "unittest.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA17_: ;
	nimln_(347, "unittest.nim");
	T19_ = (NIM_BOOL)0;
	if ((NU)(((NI) 0)) >= (NU)(beforeAndAfter->Sup.len)) raiseIndexError();
	T19_ = nsuStartsWith(matcher, beforeAndAfter->data[((NI) 0)]);
	if (!(T19_)) goto LA20_;
	if ((NU)(((NI) 1)) >= (NU)(beforeAndAfter->Sup.len)) raiseIndexError();
	T19_ = nsuEndsWith(matcher, beforeAndAfter->data[((NI) 1)]);
	LA20_: ;
	result = T19_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter_pLZsRuqSngMO8AW9bwoOkuA)(NimStringDesc* suiteName, NimStringDesc* testName, NimStringDesc* filter) {
	NIM_BOOL result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* suiteAndTestFilters;
	NIM_BOOL T14_;
	nimfr_("matchFilter", "unittest.nim");
{	result = (NIM_BOOL)0;
	nimln_(350, "unittest.nim");
	{
		if (!((filter) && (filter)->Sup.len == 0)) goto LA3_;
		nimln_(351, "unittest.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(352, "unittest.nim");
	{
		if (!eqStrings(testName, filter)) goto LA7_;
		nimln_(354, "unittest.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(355, "unittest.nim");
	suiteAndTestFilters = nsuSplitString(filter, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_57), ((NI) 1));
	nimln_(357, "unittest.nim");
	{
		NI T11_;
		NimStringDesc* test_f;
		T11_ = (suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0);
		if (!(T11_ == ((NI) 1))) goto LA12_;
		nimln_(359, "unittest.nim");
		if ((NU)(((NI) 0)) >= (NU)(suiteAndTestFilters->Sup.len)) raiseIndexError();
		test_f = suiteAndTestFilters->data[((NI) 0)];
		nimln_(360, "unittest.nim");
		result = glob_C0DsE6YhGRKuvHmSh8PDlg(testName, test_f);
		goto BeforeRet_;
	}
	LA12_: ;
	nimln_(362, "unittest.nim");
	T14_ = (NIM_BOOL)0;
	if ((NU)(((NI) 0)) >= (NU)(suiteAndTestFilters->Sup.len)) raiseIndexError();
	T14_ = glob_C0DsE6YhGRKuvHmSh8PDlg(suiteName, suiteAndTestFilters->data[((NI) 0)]);
	if (!(T14_)) goto LA15_;
	if ((NU)(((NI) 1)) >= (NU)(suiteAndTestFilters->Sup.len)) raiseIndexError();
	T14_ = glob_C0DsE6YhGRKuvHmSh8PDlg(testName, suiteAndTestFilters->data[((NI) 1)]);
	LA15_: ;
	result = T14_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "sets.nim");
	result = (NIM_BOOL)0;
	nimln_(63, "sets.nim");
	nimln_(398, "system.nim");
	nimln_(63, "sets.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ)(NimStringDesc* currentSuiteName, NimStringDesc* testName) {
	NIM_BOOL result;
	nimfr_("shouldRun", "unittest.nim");
{	result = (NIM_BOOL)0;
	nimln_(369, "unittest.nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = len_0AUATxCKyjOFDOv0xWITWA(testsFilters_Xhcy9bMKRibp73mpqIGgoPA);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(370, "unittest.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA4_: ;
	{
		NimStringDesc* f;
		f = (NimStringDesc*)0;
		nimln_(119, "sets.nim");
		{
			NIM_BOOL T9_;
			T9_ = (NIM_BOOL)0;
			T9_ = isValid_6eOTx6voj6zxXrOLagnuRg(testsFilters_Xhcy9bMKRibp73mpqIGgoPA);
			if (!!(T9_)) goto LA10_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_58));
		}
		LA10_: ;
		{
			NI h;
			NI colontmp_;
			NI T13_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(120, "sets.nim");
			T13_ = (testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data ? (testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len-1) : -1);
			colontmp_ = T13_;
			nimln_(2045, "system.nim");
			res = ((NI) 0);
			{
				nimln_(2046, "system.nim");
				while (1) {
					NI TM_Um3CQPZ9bILAIolZOsxNIaw_59;
					if (!(res <= colontmp_)) goto LA15;
					nimln_(2047, "system.nim");
					h = res;
					nimln_(121, "sets.nim");
					{
						NIM_BOOL T18_;
						if ((NU)(h) >= (NU)(testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len)) raiseIndexError();
						T18_ = (NIM_BOOL)0;
						T18_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data->data[h].Field0);
						if (!T18_) goto LA19_;
						if ((NU)(h) >= (NU)(testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len)) raiseIndexError();
						f = testsFilters_Xhcy9bMKRibp73mpqIGgoPA.data->data[h].Field1;
						nimln_(373, "unittest.nim");
						{
							NIM_BOOL T23_;
							T23_ = (NIM_BOOL)0;
							T23_ = matchFilter_pLZsRuqSngMO8AW9bwoOkuA(currentSuiteName, testName, f);
							if (!T23_) goto LA24_;
							nimln_(374, "unittest.nim");
							result = NIM_TRUE;
							goto BeforeRet_;
						}
						LA24_: ;
					}
					LA19_: ;
					nimln_(2048, "system.nim");
					TM_Um3CQPZ9bILAIolZOsxNIaw_59 = addInt(res, ((NI) 1));
					res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_59);
				} LA15: ;
			}
		}
	}
	nimln_(376, "unittest.nim");
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void) {
	nimfr_("ensureInitialized", "unittest.nim");
	nimln_(379, "unittest.nim");
	{
		NIM_BOOL T3_;
		tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__z9cxc4k8iqgnw41zdA8grdw(formatters_55U7g4zhjHV9bCI6emTgDiA, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(380, "unittest.nim");
		if (formatters_55U7g4zhjHV9bCI6emTgDiA) { nimGCunrefRC1(formatters_55U7g4zhjHV9bCI6emTgDiA); formatters_55U7g4zhjHV9bCI6emTgDiA = NIM_NIL; }
		formatters_55U7g4zhjHV9bCI6emTgDiA = (tySequence_2gM6knqz8MaAY9c4MAR2ztg*) newSeqRC1((&NTI_2gM6knqz8MaAY9c4MAR2ztg_), 1);
		T6_ = (tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
		T6_ = defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg();
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[0]), &T6_->Sup);
	}
	LA4_: ;
	nimln_(382, "unittest.nim");
	{
		NIM_BOOL T9_;
		T9_ = (NIM_BOOL)0;
		T9_ = isValid_6eOTx6voj6zxXrOLagnuRg(testsFilters_Xhcy9bMKRibp73mpqIGgoPA);
		if (!!(T9_)) goto LA10_;
		nimln_(383, "unittest.nim");
		init_dG7qwLANa3DTWvQLq7ZA7g((&testsFilters_Xhcy9bMKRibp73mpqIGgoPA), ((NI) 64));
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(386, "unittest.nim");
			colontmp_ = paramCount_T74rCHY8RMV0X07YnKmggw();
			nimln_(2045, "system.nim");
			res = ((NI) 1);
			{
				nimln_(2046, "system.nim");
				while (1) {
					NimStringDesc* T15_;
					NI TM_Um3CQPZ9bILAIolZOsxNIaw_60;
					if (!(res <= colontmp_)) goto LA14;
					nimln_(2047, "system.nim");
					i = res;
					nimln_(387, "unittest.nim");
					T15_ = (NimStringDesc*)0;
					T15_ = paramStr_eYicl3uwirn1ppNz7OCowg(i);
					incl_I6VFHFuzEfqdUNaUfyr6kA((&testsFilters_Xhcy9bMKRibp73mpqIGgoPA), T15_);
					nimln_(2048, "system.nim");
					TM_Um3CQPZ9bILAIolZOsxNIaw_60 = addInt(res, ((NI) 1));
					res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_60);
				} LA14: ;
			}
		}
	}
	LA10_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2)(void) {
	nimfr_("suiteEnded", "unittest.nim");
	{
		tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter;
		NI i;
		NI L;
		NI T2_;
		formatter = (tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_61;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
				formatter = formatters_55U7g4zhjHV9bCI6emTgDiA->data[i];
				nimln_(393, "unittest.nim");
				suiteEnded_K2O75e2roACICAuYiNImyw(formatter);
				nimln_(3809, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_61 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_61);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_18));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "unittest.nim");
	{
		tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter;
		NI i;
		NI L;
		NI T2_;
		formatter = (tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_62;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
				formatter = formatters_55U7g4zhjHV9bCI6emTgDiA->data[i];
				nimln_(397, "unittest.nim");
				testEnded_azSnnJ3hAiHHuUdLzViJlw(formatter, testResult);
				nimln_(3809, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_62 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_62);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_18));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg) {
	NI T6_;
	NimStringDesc* T7_;
	nimfr_("checkpoint", "unittest.nim");
	nimln_(508, "unittest.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__SRlIwYUUH1G46Yee9aMIFAQ(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(509, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	}
	LA4_: ;
	nimln_(510, "unittest.nim");
	checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ)->Sup, sizeof(NimStringDesc*));
	T6_ = checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->Sup.len++;
	T7_ = (NimStringDesc*)0;
	T7_ = checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->data[T6_]; checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->data[T6_] = copyStringRC1(msg);
	if (T7_) nimGCunrefNoCycle(T7_);
	popFrame();
}

static N_INLINE(NI, nextTry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h, NI maxHash) {
	NI result;
	NI TM_Um3CQPZ9bILAIolZOsxNIaw_63;
	nimfr_("nextTry", "sets.nim");
	result = (NI)0;
	nimln_(140, "sets.nim");
	TM_Um3CQPZ9bILAIolZOsxNIaw_63 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_63) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_SaVNwZAzzx9cfbfqIaCbK7Qsets)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_Um3CQPZ9bILAIolZOsxNIaw_64;
	nimfr_("rawGet", "sets.nim");
{	result = (NI)0;
	nimln_(155, "sets.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	nimln_(156, "sets.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(157, "sets.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(143, "sets.nim");
	T5_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = (s.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(s.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(151, "sets.nim");
			T15_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T15_);
		} LA7: ;
	}
	nimln_(152, "sets.nim");
	TM_Um3CQPZ9bILAIolZOsxNIaw_64 = subInt(((NI) -1), h);
	result = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_64);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_CuJUY9aKh8Ku1t1T7BDJRuQsets)(tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg s, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_Um3CQPZ9bILAIolZOsxNIaw_65;
	nimfr_("rawGetKnownHC", "sets.nim");
{	result = (NI)0;
	nimln_(143, "sets.nim");
	T1_ = (s.data ? (s.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(144, "sets.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_UshbaKGVTNLaJdFZ6zcwsw_2sets(s.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(149, "sets.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = (s.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(s.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(s.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(150, "sets.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(151, "sets.nim");
			T11_ = (s.data ? (s.data->Sup.len-1) : -1);
			h = nextTry_iM1OyigHU0QXXBzsM5QjYAsets(h, T11_);
		} LA3: ;
	}
	nimln_(152, "sets.nim");
	TM_Um3CQPZ9bILAIolZOsxNIaw_65 = subInt(((NI) -1), h);
	result = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_65);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void) {
	nimfr_("unittest", "unittest.nim");
nimRegisterThreadLocalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_2);
nimRegisterThreadLocalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_3);
nimRegisterThreadLocalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_4);
	nimln_(155, "unittest.nim");
	abortOnError_Bte3Uiwc4Q19ago2N4C89cUA = existsEnv_vAQ9aK36dVeMFf61ovfHwJw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_5));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void) {
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_6[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_7[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_9;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_8[3] = {
"PRINT_ALL", 
"PRINT_FAILURES", 
"PRINT_NONE"};
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_21[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_23;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_22[3] = {
"OK", 
"FAILED", 
"SKIPPED"};
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_33[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_66[3];
static TNimNode TM_Um3CQPZ9bILAIolZOsxNIaw_0[23];
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.size = sizeof(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.kind = 17;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].len = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].kind = 2;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[0];
NTI_po6hYFavJCZm28qf1dR3mw_.size = sizeof(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*);
NTI_po6hYFavJCZm28qf1dR3mw_.kind = 22;
NTI_po6hYFavJCZm28qf1dR3mw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_po6hYFavJCZm28qf1dR3mw_.marker = Marker_tyRef_po6hYFavJCZm28qf1dR3mw;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.size = sizeof(tySequence_2gM6knqz8MaAY9c4MAR2ztg*);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.kind = 24;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.base = (&NTI_po6hYFavJCZm28qf1dR3mw_);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.marker = Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg;
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.kind = 17;
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_6[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[2];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, colorOutput);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].name = "colorOutput";
TM_Um3CQPZ9bILAIolZOsxNIaw_6[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[3];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.size = sizeof(tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww);
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.kind = 14;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.base = 0;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_9 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_9 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_9++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_9+4].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_9+4].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_9;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_9+4].name = TM_Um3CQPZ9bILAIolZOsxNIaw_8[TM_Um3CQPZ9bILAIolZOsxNIaw_9];
TM_Um3CQPZ9bILAIolZOsxNIaw_7[TM_Um3CQPZ9bILAIolZOsxNIaw_9] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_9+4];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_7[0];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[7];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, outputLevel);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].typ = (&NTI_7UfTrIPsm9cGDPwH9bpwJDww_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].name = "outputLevel";
TM_Um3CQPZ9bILAIolZOsxNIaw_6[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[8];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInSuite);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].name = "isInSuite";
TM_Um3CQPZ9bILAIolZOsxNIaw_6[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[9];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInTest);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].name = "isInTest";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_6[0];
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[1];
NTI_ExFEz8ninaqkX3e4eolu7g_.size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*);
NTI_ExFEz8ninaqkX3e4eolu7g_.kind = 22;
NTI_ExFEz8ninaqkX3e4eolu7g_.base = (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_);
NTI_ExFEz8ninaqkX3e4eolu7g_.marker = Marker_tyRef_ExFEz8ninaqkX3e4eolu7g;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.size = sizeof(tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ);
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.kind = 14;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.base = 0;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_23 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_23 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_23++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_23+10].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_23+10].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_23;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_23+10].name = TM_Um3CQPZ9bILAIolZOsxNIaw_22[TM_Um3CQPZ9bILAIolZOsxNIaw_23];
TM_Um3CQPZ9bILAIolZOsxNIaw_21[TM_Um3CQPZ9bILAIolZOsxNIaw_23] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_23+10];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_21[0];
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[13];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.size = sizeof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ);
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.kind = 17;
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_33[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[15];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, stream);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].typ = (&NTI_r3Wc5tOoxP8rz1DvGVTUvw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].name = "stream";
TM_Um3CQPZ9bILAIolZOsxNIaw_33[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[16];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testErrors);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].name = "testErrors";
TM_Um3CQPZ9bILAIolZOsxNIaw_33[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[17];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStartTime);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].name = "testStartTime";
TM_Um3CQPZ9bILAIolZOsxNIaw_33[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[18];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStackTrace);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].name = "testStackTrace";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_33[0];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[14];
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.size = sizeof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*);
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.kind = 22;
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.base = (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_);
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.marker = Marker_tyRef_OU9b9b9b3svfAf0YBTEFQsJag;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.size = sizeof(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ);
NTI_GEvSVSxdPWWgMGM48ywEYQ_.kind = 18;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.base = 0;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.flags = 2;
TM_Um3CQPZ9bILAIolZOsxNIaw_66[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[20];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].offset = offsetof(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ, suiteName);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].name = "suiteName";
TM_Um3CQPZ9bILAIolZOsxNIaw_66[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[21];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].offset = offsetof(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ, testName);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].name = "testName";
TM_Um3CQPZ9bILAIolZOsxNIaw_66[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[22];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].offset = offsetof(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ, status);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].typ = (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].name = "status";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_66[0];
NTI_GEvSVSxdPWWgMGM48ywEYQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[19];
}

